import { MatchesClient } from "./matches-client";
import type { MatchCardData } from "@/components/matches/match-card";

const matches: (MatchCardData & { postedToday?: boolean })[] = [
  {
    id: "stripe-1",
    company: "Stripe",
    role: "Senior Frontend Engineer",
    location: "San Francisco, CA",
    score: 94,
    time: "2h ago",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Design systems"],
    avatarClass: "bg-emerald-500",
    postedToday: true,
  },
  {
    id: "linear-1",
    company: "Linear",
    role: "Staff Engineer, Platform",
    location: "Remote",
    score: 89,
    time: "4h ago",
    skills: ["TypeScript", "Node.js", "PostgreSQL", "AWS"],
    avatarClass: "bg-violet-500",
    postedToday: true,
  },
  {
    id: "vercel-1",
    company: "Vercel",
    role: "Software Engineer, DX",
    location: "Remote",
    score: 86,
    time: "6h ago",
    skills: ["React", "Next.js", "Developer tools"],
    avatarClass: "bg-blue-500",
  },
  {
    id: "notion-1",
    company: "Notion",
    role: "Frontend Engineer",
    location: "New York, NY",
    score: 78,
    time: "1d ago",
    skills: ["React", "TypeScript", "CSS"],
    avatarClass: "bg-orange-500",
  },
  {
    id: "stripe-2",
    company: "Stripe",
    role: "Frontend Engineer",
    location: "Remote",
    score: 91,
    time: "1d ago",
    skills: ["React", "TypeScript", "Payments"],
    avatarClass: "bg-emerald-500",
  },
  {
    id: "linear-2",
    company: "Linear",
    role: "Senior Product Engineer",
    location: "San Francisco, CA",
    score: 85,
    time: "2d ago",
    skills: ["React", "TypeScript", "Product"],
    avatarClass: "bg-violet-500",
  },
  {
    id: "vercel-2",
    company: "Vercel",
    role: "Senior Frontend Engineer",
    location: "Remote",
    score: 82,
    time: "2d ago",
    skills: ["Next.js", "React", "Edge"],
    avatarClass: "bg-blue-500",
  },
  {
    id: "notion-2",
    company: "Notion",
    role: "Senior Frontend Engineer",
    location: "San Francisco, CA",
    score: 80,
    time: "3d ago",
    skills: ["React", "Performance", "Accessibility"],
    avatarClass: "bg-orange-500",
  },
  {
    id: "figma-1",
    company: "Figma",
    role: "Software Engineer, UI",
    location: "San Francisco, CA",
    score: 76,
    time: "3d ago",
    skills: ["TypeScript", "WebGL", "React"],
    avatarClass: "bg-pink-500",
  },
  {
    id: "figma-2",
    company: "Figma",
    role: "Frontend Engineer",
    location: "New York, NY",
    score: 72,
    time: "4d ago",
    skills: ["React", "C++", "Canvas"],
    avatarClass: "bg-pink-500",
  },
  {
    id: "airbnb-1",
    company: "Airbnb",
    role: "Senior Software Engineer",
    location: "Remote",
    score: 68,
    time: "5d ago",
    skills: ["React", "GraphQL", "Ruby"],
    avatarClass: "bg-rose-500",
  },
  {
    id: "airbnb-2",
    company: "Airbnb",
    role: "Frontend Engineer, Host",
    location: "San Francisco, CA",
    score: 65,
    time: "1w ago",
    skills: ["React", "TypeScript", "Mobile web"],
    avatarClass: "bg-rose-500",
  },
];

export default function MatchesPage() {
  return <MatchesClient initialMatches={matches} />;
}
